### ISSUE TITLE
[Issue] TTFs aren't working

### ISSUE THREAD

**Issue by lubeda** [trip5/Matrix-Fonts#6]
### Information

Hi, besides the positive vibes, i found an issue.

On compiling the latest  EspHoMaTriX with your TTFs i got this error:
`ERROR Could not load truetype file /config/esphome/MatrixChunky8.ttf: invalid pixel size`

```yaml
font:
  - file: MatrixChunky8.ttf
    id: default_font
    size: 8
    glyphs:  |
      ! "#$%&'()€*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz°

```

In the windows TTF viewer, they are all white

![image](https://github.com/trip5/Matrix-Fonts/assets/17859549/9f7bfcac-205b-45bd-b5b6-1d62d9477261)
